package edu.example.part1.interfaces;

import edu.example.part1.pojo.Population;
import retrofit2.Call;
import retrofit2.http.GET;

/**
 * Created by Joy on 3/19/18.
 * An interface that defines a method to
 * retrieves JSON data from an HTTP server.
 * The default implementation for the interface
 * is generated by RetroFit
 */

public interface WebService {
    @GET("/tutorial/jsonparsetutorial.txt")
    Call<Population> getPops();
}
